BOXSIZE = 40
GAP = 10

BOARDWIDTH = 10
BOARDHEIGHT = 7

WIDTH = (BOXSIZE + GAP) * BOARDWIDTH + GAP
HEIGHT = (BOXSIZE + GAP) * BOARDHEIGHT + GAP
TITLE = 'MATCHING!'
XMARGIN = (WIDTH - (BOARDWIDTH * (BOXSIZE + GAP))) // 2
YMARGIN = (HEIGHT - (BOARDHEIGHT * (BOXSIZE + GAP))) // 2

#            R    G    B
GRAY     = (100, 100, 100)
NAVYBLUE = ( 60,  60, 100)
WHITE    = (255, 255, 255)
RED      = (255,   0,   0)
GREEN    = (  0, 255,   0)
BLUE     = (  0,   0, 255)
YELLOW   = (255, 255,   0)
ORANGE   = (255, 128,   0)
PURPLE   = (255,   0, 255)
CYAN     = (  0, 255, 255)
BGCOLOR = NAVYBLUE
LIGHTBGCOLOR = GRAY
BOXCOLOR = WHITE
HIGHLIGHTCOLOR = BLUE

DONUT = 'donut'
SQUARE = 'square'
CROSS = 'cross'
LINES = 'lines'
DIAMOND = 'diamond'

ALLCOLORS = (RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE, CYAN)
ALLSHAPES = (DONUT, SQUARE, CROSS, LINES, DIAMOND)