from colors import *
BOXSIZE = 40
GAP = 10

BOARDWIDTH = 10
BOARDHEIGHT = 7

WIDTH = (BOXSIZE + GAP) * BOARDWIDTH + GAP
HEIGHT = (BOXSIZE + GAP) * BOARDHEIGHT + GAP
TITLE = 'Memory!'
FPS = 60

BGCOLOR = NAVY
LIGHTBGCOLOR = GRAY
BOXCOLOR = WHITE
HIGHLIGHTCOLOR = BLUE

DONUT = 'donut'
SQUARE = 'square'
CROSS = 'cross'
LINES = 'lines'
DIAMOND = 'diamond'

ALLCOLORS = (RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE, CYAN)
ALLSHAPES = (DONUT, SQUARE, CROSS, LINES, DIAMOND)